/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jltxgcy_dynamicdex_DexLoader */

#ifndef _Included_com_jltxgcy_dynamicdex_DexLoader
#define _Included_com_jltxgcy_dynamicdex_DexLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jltxgcy_dynamicdex_DexLoader
 * Method:    load
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jltxgcy_dynamicdex_DexLoader_load
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_jltxgcy_dynamicdex_DexLoader
 * Method:    run
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jltxgcy_dynamicdex_DexLoader_run
  (JNIEnv *, jclass);


#ifdef __cplusplus
}
#endif
#endif
