/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_fixdex_FindCode */

#ifndef _Included_com_example_fixdex_FindCode
#define _Included_com_example_fixdex_FindCode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_fixdex_FindCode
 * Method:    findCode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_fixdex_FindCode_findCode
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
